=== brittonhayes/armactl/reforger/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "dedicatedServerId": {
        "type": "string"
      },
      "region": {
        "title": "ISO 3166-1 Alpha-2 Country code",
        "description": "A valid 2-digit ISO country code (ISO 3166-1 alpha-2), or, an array of valid ISO codes.",
        "type": "string", "pattern": "^([A-Z]{2})$|^([A-Z]{2})-([A-Z0-9]{2,3})$"
        
      },
      "gameHostBindAddress": {
        "type": "string",
        "format": "ipv4"
      },
      "gameHostBindPort": {
        "type": "integer"
      },
      "gameHostRegisterBindAddress": {
        "type": "string",
        "format": "ipv4"
      },
      "gameHostRegisterPort": {
        "type": "integer"
      },
      "adminPassword": {
        "type": "string"
      },
      "game": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "scenarioId": {
            "type": "string"
          },
          "playerCountLimit": {
            "type": "integer"
          },
          "autoJoinable": {
            "type": "boolean"
          },
          "visible": {
            "type": "boolean"
          },
          "gameProperties": {
            "type": "object",
            "properties": {
              "serverMaxViewDistance": {
                "type": "integer"
              },
              "serverMinGrassDistance": {
                "type": "integer"
              },
              "networkViewDistance": {
                "type": "integer"
              },
              "disableThirdPerson": {
                "type": "boolean"
              },
              "fastValidation": {
                "type": "boolean"
              },
              "battlEye": {
                "type": "boolean"
              }
            },
            "required": [
              "serverMaxViewDistance",
              "serverMinGrassDistance",
              "networkViewDistance",
              "disableThirdPerson",
              "fastValidation",
              "battlEye"
            ]
          },
          "mods": {
            "type": "array",
            "items": [
              {
                "type": "object",
                "properties": {
                  "modId": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "version": {
                    "type": "string"
                  }
                },
                "required": [
                  "modId",
                  "name",
                  "version"
                ]
              }
            ]
          }
        },
        "required": [
          "name",
          "password",
          "scenarioId",
          "playerCountLimit",
          "autoJoinable",
          "visible",
          "gameProperties",
          "mods"
        ]
      },
      "a2sQueryEnabled": {
        "type": "boolean"
      },
      "steamQueryPort": {
        "type": "integer"
      }
    },
    "required": [
      "dedicatedServerId",
      "region",
      "gameHostBindAddress",
      "gameHostBindPort",
      "gameHostRegisterBindAddress",
      "gameHostRegisterPort",
      "adminPassword",
      "game",
      "a2sQueryEnabled",
      "steamQueryPort"
    ]
  }

=== brittonhayes/armactl/test/reforger.server.json
{
    "dedicatedServerId": "",
    "region": "US",
    "gameHostBindAddress": "0.0.0.0",
    "gameHostBindPort": 32001,
    "gameHostRegisterBindAddress": "73.111.111.11",
    "gameHostRegisterPort": 32001,
    "adminPassword": "adminpassword",
    "game": {
        "name": "Server Name",
        "password": "password",
        "scenarioId": "{59AD59368755F41A}Missions/21_GM_Eden.conf",
        "playerCountLimit": 10,
        "autoJoinable": false,
        "visible": true,
        "gameProperties": {
            "serverMaxViewDistance": 1600,
            "serverMinGrassDistance": 0,
            "networkViewDistance": 500,
            "disableThirdPerson": false,
            "fastValidation": true,
            "battlEye": true
        },
        "mods": [
            { 
                "modId": "5994AD5A9F33BE57",
                "name": "Game Master FX",
                "version": "1.0.51" 
            }
        ]
    },
    "a2sQueryEnabled": true,
    "steamQueryPort": 17777
}
